image:
  file: .gitpod.Dockerfile

tasks:
  -name: azure
    init: |
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Run
    command: dotnet run

vscode:
  extensions:
    - muhammad-sammy.csharp
